-- Events and tournament support tables for RankTiers

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  game text not null,
  kit text not null,
  tiers text[] not null default '{}',
  bracket jsonb not null default '{"rounds": []}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists events_game_kit_idx on public.events (game, kit);

create table if not exists public.player_event_records (
  event_id bigint not null references public.events(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  wins integer not null default 0 check (wins >= 0),
  losses integer not null default 0 check (losses >= 0),
  created_at timestamptz not null default now(),
  primary key (event_id, player_id)
);

create index if not exists player_event_records_player_idx on public.player_event_records (player_id);
